### ISSUE TITLE
android-kubernetes-blockchain Vs. Bigchaindb

### ISSUE THREAD

**Issue by adonnini** [IBM/android-kubernetes-blockchain#18]
Hi,
Currently, My Android location tracking and mobility profile production app is integrated with Bigchaindb based blockchain at present using the Bighchaindb testnet.

Briefly, I use the blockchain to build a universally accessible database of access points, determine on the fly indoor/outdoor location of a user, and post user location information and mobility profiles on the blockchain.

After a quick review of your environment, I am not sure I could do the same in your environment at least not without building your entire environment locally.

Is you blockchain implementation meant to be used as I describe above (my current use of the Bigchaindb based blockchain)?

Thank,

Alex Donnini

**Comment by AnthonyAmanse** [comment]
Hi, yes - this repo is meant to be used with Hyperledger Fabric
